checkpoint:
  classes:
  - mito
  path: /groups/cellmap/cellmap/zouinkhim/c-elegen/v3/train/runs/20250806_mito_mouse_distance_16nm/model_checkpoint_362000
paths:
  log_dir: /nrs/cellmap/zouinkhim/tensorboard/setup_15
  yaml_file: 20250806_mito_mouse.yaml
run:
  batch_size: 14
  l_rate: 5.0e-05
  labels:
  - mito
  - mito
  - mito
  - mito
  - mito
  - mito
  - mito
  - mito
  - mito
  - mito
  - mito
  - mito
  - mito
  name: setup_15
  voxel_size: 16
