checkpoint:
  classes:
  - mito
  path: /groups/cellmap/cellmap/zouinkhim/c-elegen/v3/train/runs/20250725_mito_all_mixed_distance_16nm/model_checkpoint_372000
paths:
  log_dir: /nrs/cellmap/zouinkhim/tensorboard/setup_18
  yaml_file: 20250914_all_mitos.yaml
run:
  batch_size: 14
  l_rate: 5.0e-05
  labels:
  - mito
  lsd: True
  name: setup_18
  voxel_size: 32
